apiVersion: batch/v1
kind: Job
metadata:
  name: content-injector
spec:
  template:
    spec:
      containers:
      - name: injector-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        volumeMounts:
        - name: nfs-mount
          mountPath: /mnt/nfs
        args:
          - |
            # Simple HTML content
            html_content='
            <!DOCTYPE html>
            <html>
            <head><title>My App</title></head>
            <body><h1>Hello World</h1></body>
            </html>
            '
            # Create index.html in the container
            echo "$html_content" > /index.html

            # Copy index.html to the mounted NFS volume
            cp /index.html /mnt/nfs/index.html
      restartPolicy: Never
      volumes:
      - name: nfs-mount
        persistentVolumeClaim:
          claimName: webapp-content-pvc