---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webapp-content-pvc
spec:
  storageClassName: "nfs-web-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi