---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 80