apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-app
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nfs-content-volume
      volumes:
      - name: nfs-content-volume
        persistentVolumeClaim:
          claimName: webapp-content-pvc